<?php

require_once("sql.php");
require_once("Lang.php");
require_once("Settings.php");
require_once("Utils.php");
require_once("User.php");
require_once("CompanyService.php");
require_once("pages/CorePage.php");
require_once("pages/BookingPage.php");
require_once("pages/BookingListPage.php");
require_once("pages/BookingSuccessfulPage.php");
require_once("pages/BookingValidatePage.php");
require_once("pages/BookingDeletePage.php");
require_once("pages/BookingDeleteSuccessfulPage.php");
require_once("pages/LoginPage.php");
require_once("pages/LoginWithTajNumberPage.php");
require_once("pages/RegistrationPage.php");
require_once("pages/ProfilePage.php");
require_once("pages/PasswordSendPage.php");
require_once("pages/ValidateLoginPage.php");
require_once("pages/ValidationSuccessfulPage.php");
require_once("pages/DocumentsPage.php");
require_once("pages/BeutalokPage.php");
require_once("pages/LeletekPage.php");
require_once("Page.php");
require_once("DocAgent.php");
require_once("BookingService.php");
require_once("PrintService.php");

require_once("other/phpmailer/class.phpmailer.php");
require_once("other/seeme-gateway-class.php");
require_once("other/google-drive-downloader.php");
